export const APP_TITLE = "mickey's shopping list";
export const LIGHT_BLUE = '#5CB3EA';
export const DARK_BLUE = '#1298ED';
export const ICON_SIZE = 20;
export const ICON_SIZE_LARGE = 28;
export const RADIUS = 8;
export const ROW_HEIGHT = 38;
export const ROW_GAP = 10;
export const SCROLL_DISTANCE = 20;
